### ISSUE TITLE
Pelican Driver requires all parameters on each actuation

### ISSUE THREAD

**Issue by gtfierro** [SoftwareDefinedBuildings/bw2-contrib#8]
Venstar had a similar issue

**Comment by immesys** [comment]
Wait you can't just say setpoint=foo ?

**Comment by immesys** [comment]
Thats dumb, shouldfix

**Comment by gtfierro** [comment]
I fixed it on the Venstar; shouldn't be too difficult to do here as well

**Comment by gtfierro** [comment]
https://github.com/SoftwareDefinedBuildings/bw2-contrib/pull/9
